table sucursales {
  id int [pk, increment]
  nombre varchar(100) [not null]
  direccion varchar(255)
  telefono varchar(15)
  activo boolean [default: true]
}

table categorias {
  id int [pk, increment]     
  nombre varchar(255)
  descripcion text
}

table productos {
  id int [pk, increment]
  categoria_id int [ref: > categorias.id]

  codigo varchar(50) [unique, not null]
  nombre varchar(255) [not null]
  descripcion text
  imagen varchar(255)
  precio_compra decimal(10, 2) [not null]
  precio_venta decimal(10, 2) [not null]
  stock_minimo int [default: 0]
  stock_maximo int [default: 0]
  unidad_medida varchar(50) [not null]
  estado boolean [default: true]
}

table proveedores {
  id int [pk, increment]
  empresa varchar(100) 
  direccion varchar(255)
  nombre varchar(100) [not null]
  telefono varchar(15)
  email varchar(100)
}

table lotes {
  id int [pk, increment]
  producto_id int [ref: > productos.id]
  proveedor_id int [ref: > proveedores.id]

  codigo_lote varchar(50) [not null]
  fecha_entrada date
  fecha_vencimiento date
  cantidad_inicial int [not null]
  cantidad_actual int [not null]
  precio_compra decimal(10, 2) [null]
  precio_venta decimal(10, 2) [null]
  estado boolean [default: true]
}

table inventario_sucursal_lote {
  id int [pk, increment]
  lote_id int [ref: > lotes.id]
  sucursal_id int [ref: > sucursales.id]
  cantidad_en_sucursal int [not null]
}

table movimientos_inventario {
  id int [pk, increment]
  producto_id int [ref: > productos.id]
  lote_id int [ref: > lotes.id]
  sucursal_id int [ref: > sucursales.id]

  tipo_movimiento varchar(50) [not null]
  cantidad int [not null]
  fecha datetime [default: `CURRENT_TIMESTAMP`]
  observaciones text
}
table compras {
  id int [pk, increment]
  proveedor_id int [ref: > proveedores.id]

  fecha datetime [default: `CURRENT_TIMESTAMP`]
  total decimal(10, 2) [not null]
  estado varchar(50) [default: 'pendiente']
  observaciones text
}

table detalle_compras {
  id int [pk, increment]
  compra_id int [ref: > compras.id]
  producto_id int [ref: > productos.id]
  lote_id int [ref: > lotes.id]
  cantidad int [not null]
  precio_unitario decimal(10, 2) [not null]
  subtotal decimal(10, 2) [not null]
}